- name: Create openvpn config file
  tags: [configure]
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/{{openvpn_config_file}}.conf"
    owner: root
    group: root
  notify:
    - restart openvpn

- name: Install LDAP config
  tags: [configure]
  template:
    src: ldap.conf.j2
    dest: "{{ openvpn_base_dir }}/auth/ldap.conf"
    owner: root
    group: root
  when: openvpn_use_ldap

- name: Copy openvpn logrotate config file
  tags: [configure]
  copy:
    src: openvpn_logrotate.conf
    dest: /etc/logrotate.d/openvpn.conf
    owner: root
    group: root
    mode: 0400
  when: ansible_os_family != 'Solaris'

- name: Setup openvpn auto-start & start
  tags: [configure]
  service:
    name: "{{openvpn_service_name}}"
    enabled: yes
    state: started
